title: "Abrorkuja Latipov | Portfolio"
author: "Abror Latif"
description: "Portfolio of a data science student focused on machine learning, Python, and real-world projects. Includes projects, skills, and contact info."
theme: minima
